apps/supervision/urls.py
from django.urls import path, include

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers

from .views import MovimientoCreateView, MovimientoUpdateView, MovimientoListView, MovimientoInformeFormView, MovimientoInformeImprimir, \
    EntradaListView, EntradaCreateView, EntradaUpdateView, EntradaDetailView, \
    DetalleDepuracionCreateView, DetalleDepuracionUpdateView, DetalleDeleteView, \
    MovimientoInforme, \
    MovimientoRestList


router = routers.SimpleRouter()
router.register(r'movimientos', MovimientoRestList)


urlpatterns = [
    # MOVIMIENTO
    path('movimiento/add/', MovimientoCreateView.as_view(), name='movimiento_add'),
    path('movimiento/<int:pk>/', MovimientoUpdateView.as_view(), name='movimiento_update'),
    path('movimiento/list/', MovimientoListView.as_view(), name='movimiento_list'),
    path('movimiento/informe/', MovimientoInformeFormView.as_view(), name='movimiento_informe'),
    path('movimiento/informe/print/', MovimientoInformeImprimir.as_view(), name='movimiento_informe_print'),

    # INFORME DE MOVIMIENTOS CON FUNCIONES
    #path('movimiento/informe/json/', MovimientoInforme, name='movimiento_informe_funcion'),

    
    # REST
    path('api/', include(router.urls)),


    # DEPURACION
    path('depuracion/add/', EntradaCreateView.as_view(), name='entrada_add'),
    path('depuracion/<int:pk>/', EntradaUpdateView.as_view(), name='entrada_update'),
    path('depuracion/list/', EntradaListView.as_view(), name='entrada_list'),
    path('depuracion/detail/<int:pk>/', EntradaDetailView.as_view(), name='entrada_detail'),
    path('depuracion/detalle/add/', DetalleDepuracionCreateView.as_view(), name='detalle_add'),
    path('depuracion/detalle/<int:pk>/', DetalleDepuracionUpdateView.as_view(), name='detalle_update'),
    path('depuracion/detalle/quitar/<int:pk>/', DetalleDeleteView.as_view(), name='detalle_delete'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

#import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),

    #path('__debug__/', include(debug_toolbar.urls)),
    
    # Urls de las apps
    path('falta/', include('apps.faltas.urls')),
    path('', include('apps.evaluaciones.urls')),
    path('indicador/', include('apps.indicadores.urls')),
    path('perfil/', include('apps.registration.urls')),
    path('apuntes/', include('apps.apuntes.urls')),
    path('entregas/', include('apps.equipamientos.urls')),
    path('planificacion/', include('apps.tareas.urls')),
    path('supervision/', include('apps.supervision.urls')),
    path('bodega/', include('apps.bodega.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/supervision/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User


# Modelo Abstracto para poder ser heredado
class ControlCreaciones(models.Model):
    creado = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    actualizado = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        abstract = True

# Tipos de movimientos Solicitud y Devolución
class TipoMovimiento(models.Model):
    tipo = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.tipo)


# Supervisión de Movimientos con herencia al control de Creaciones
class Movimiento(ControlCreaciones):

    movimiento = models.IntegerField(null=False, blank=False, unique=True)
    tipo = models.ForeignKey(TipoMovimiento, related_name='relMovimientoTipo', on_delete=models.CASCADE)
    desecho = models.BooleanField(default=False)
    dispositivo = models.CharField(max_length=100, null=False, blank=False)
    cantidad = models.PositiveSmallIntegerField(null=False, blank=False, default=0)
    fecha = models.DateField(default=datetime.datetime.now, null=False, blank=False)
    entrega = models.ForeignKey(User, related_name='relMovimientoUsuarioEntrega', on_delete=models.CASCADE)
    recibe = models.ForeignKey(User, related_name='relMovimientoUsuarioRecibe', on_delete=models.CASCADE)
    creado_en_suni = models.BooleanField(default=False)
    hoja_impresa = models.BooleanField(default=False)
    genera_kardex = models.BooleanField(default=False)
    kardex = models.IntegerField(verbose_name='No. Kardex', null=True, blank=True)
    registro_en_correo = models.BooleanField(default=False)
    observaciones = models.TextField(verbose_name='Observaciones', null=True, blank=True)
    supervisado_por = models.ForeignKey(User, related_name='relMovimientoUsuarioSupervisa', on_delete=models.CASCADE)
    supervision_completada = models.BooleanField(default=False)
        
    def __str__(self):
        return '{}'.format(self.movimiento)





# Supervisión de SUNI-Entradas-Depuración a Kardex.
class Entrada(ControlCreaciones):

    entrada = models.PositiveSmallIntegerField(null=False, blank=False)
    fecha = models.DateField(default=datetime.datetime.now, null=False, blank=False)
    entrega = models.ForeignKey(User, related_name='relEntradaUsuarioEntrega', on_delete=models.CASCADE)
    recibe = models.ForeignKey(User, related_name='relEntradaUsuarioRecibe', on_delete=models.CASCADE)
    creado_en_suni = models.BooleanField(default=False)
    hoja_impresa = models.BooleanField(default=False)
    kardex = models.IntegerField(verbose_name='No. Kardex', null=True, blank=True)
    registro_en_correo = models.BooleanField(default=False)
    observaciones = models.TextField(verbose_name='Observaciones', null=True, blank=True)
    supervisado_por = models.ForeignKey(User, related_name='relEntradaUsuarioSupervisa', on_delete=models.CASCADE)
    cerrar = models.BooleanField(default=False)
        
    def __str__(self):
        return '{}'.format(self.entrada)



# Detalle de la depuración
class DetalleDepuracion(models.Model):

    entrada = models.ForeignKey(Entrada, related_name='relDepuracionEntrada', on_delete=models.CASCADE)
    dispositivo = models.CharField(max_length=100)
    cantidad = models.PositiveSmallIntegerField(null=False, blank=False, default=0)
    observaciones = models.TextField(verbose_name='Observaciones', null=True, blank=True)
        
    def __str__(self):
        return '{} - {}'.format(self.cantidad, self.dispositivo)

apps/supervision/forms.py
from django import forms

from django.forms import ModelForm
from .models import Movimiento, Entrada, DetalleDepuracion, TipoMovimiento


""" Formulario de Movimientos y kardex """
class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        fields = '__all__'
        widgets = {
            'tipo': forms.Select(attrs={"id":"select2"}),
            'fecha': forms.DateInput(attrs={'class':'myDatepicker2'}),
            'entrega': forms.Select(attrs={"id":"select2_1"}),
            'recibe': forms.Select(attrs={"id":"select2_2"}),
            'supervisado_por': forms.Select(attrs={"id":"select2_3"}),
            'completado': forms.CheckboxInput(attrs={'class':'switch'}),
            'creado': forms.HiddenInput(),
            'actualizado': forms.HiddenInput()
        }
    
    def __init__(self, *args, **kwargs):
        super(MovimientoForm, self).__init__(*args, **kwargs)
        self.fields['entrega'].label_from_instance = lambda obj: "%s" % obj.get_full_name()
        self.fields['recibe'].label_from_instance = lambda obj: "%s" % obj.get_full_name()
        self.fields['supervisado_por'].label_from_instance = lambda obj: "%s" % obj.get_full_name()




class EntradaForm(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = '__all__'
        widgets = {
            'fecha': forms.DateInput(attrs={'class':'myDatepicker2'}),
            'entrega': forms.Select(attrs={"id":"select2_1"}),
            'recibe': forms.Select(attrs={"id":"select2_2"}),
            'supervisado_por': forms.Select(attrs={"id":"select2_3"}),
            'cerrar': forms.CheckboxInput(attrs={'class':'switch'}),
            'creado': forms.HiddenInput(),
            'actualizado': forms.HiddenInput()
        }
    
    def __init__(self, *args, **kwargs):
        super(EntradaForm, self).__init__(*args, **kwargs)
        self.fields['entrega'].label_from_instance = lambda obj: "%s" % obj.get_full_name()
        self.fields['recibe'].label_from_instance = lambda obj: "%s" % obj.get_full_name()
        self.fields['supervisado_por'].label_from_instance = lambda obj: "%s" % obj.get_full_name()


class DetalleDepuracionForm(forms.ModelForm):
    class Meta:
        model = DetalleDepuracion
        fields = '__all__'
        widgets = {
            'entrada': forms.HiddenInput(),
        }


class MovimientosInformeForm(forms.Form):
    """Formulario que Controla los filtros para poder hacer busquedas
    """
    tipo = forms.ModelChoiceField(
        queryset=TipoMovimiento.objects.all(),
        label='Tipo',
        required=False,
        widget=forms.Select(attrs={'class': 'form-control select2'}))
    fecha_min = forms.CharField(
        label='Fecha (inicial)',
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control myDatepickerConsulta1'}))
    fecha_max = forms.CharField(
        label='Fecha (final)',
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control myDatepickerConsulta2'}))

apps/supervision/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, FormView
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse, HttpResponse
from django.core import serializers

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin


from .models import Movimiento, TipoMovimiento, Entrada, DetalleDepuracion, User
from .forms import MovimientoForm, EntradaForm, DetalleDepuracionForm, MovimientosInformeForm
from .serializers import MovimientoSerializer, MovimientoInformeSerializer, TipoSerializer, UsuariosSerializer
from .filters import MovimientoFilter


from rest_framework import generics

from rest_framework import viewsets

""" Movimientos Solicitudes / Devoluciones """
class MovimientoListView(GroupRequiredMixin, LoginRequiredMixin, ListView):
    group_required = [u"Tecnicos"]
    model = Movimiento
    template_name = 'supervision/movimiento_list.html'

class MovimientoCreateView(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    group_required = [u"admin", u"Supervisores",]
    model = Movimiento
    form_class = MovimientoForm
    template_name = 'supervision/movimiento_add.html'
    success_url = reverse_lazy('movimiento_list')

class MovimientoUpdateView(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    group_required = [u"admin", u"Supervisores",]
    model = Movimiento
    form_class = MovimientoForm
    template_name = 'supervision/movimiento_add.html'
    success_url = reverse_lazy('movimiento_list')


class MovimientoInformeFormView(LoginRequiredMixin, FormView):
    """Vista encarga de gestionar el listado de :class:`Proyecto`,obteniendo los datos necesarios
    por medio del metodo GET nos muestra el template proyecto_list.
    """
    model = Movimiento
    form_class = MovimientosInformeForm
    template_name = 'supervision/movimiento_informe.html'

class MovimientoInformeImprimir(LoginRequiredMixin, ListView):
    """Vista encarga de gestionar el listado de :class:`Proyecto`,obteniendo los datos necesarios
    por medio del metodo GET nos muestra el template proyecto_list.
    """
    model = Movimiento
    form_class = MovimientosInformeForm
    template_name = 'supervision/movimiento_informe_imprimir.html'


class MovimientoRestList(viewsets.ModelViewSet):
    serializer_class = MovimientoSerializer
    queryset = Movimiento.objects.all()
    filter_class = MovimientoFilter


""" Generar el Informe de Movimiento -- ESTA FORMA SÓLO FUE UN ENSAYO, NO SE UTILIZARÁ"""
def MovimientoInforme(request):
    if request.is_ajax():
        informe = Movimiento.objects.filter(fecha__range=(request.GET['fecha_min'], request.GET['fecha_max']))
        # Declarar diccionario
        f = []

        # Recorrer el resultado de la consulta e ir generando el diccionario
        for x in informe:

            # Cambiar la palabra True por Completado o False por Pendiente
            if(x.supervision_completada):
                estado = 'Completado'
            else:
                estado = 'Pendiente'
            # Crear para el diccionario
            fila = {'movimiento':x.movimiento,'fecha':x.fecha,'tipo':x.tipo.tipo,'dispositivo':x.dispositivo,'entrega':(x.entrega.first_name + ' ' + x.entrega.last_name),'recibe':(x.recibe.first_name + ' ' + x.recibe.last_name),'kardex':x.kardex,'supervisado':(x.supervisado_por.first_name + ' ' + x.supervisado_por.last_name),'estado':estado}

            # Agregar fila al diccionario
            f.append(fila)

        #response = serializers.serialize('json', informe)
        #return HttpResponse(response, content_type='application/json')

        # Serializar diccionario con safe=False y convertirlo a Json
        return JsonResponse(f, safe=False)
    else:
        return redirect('/')






""" Depuraciones """
class EntradaListView(GroupRequiredMixin, LoginRequiredMixin, ListView):
    group_required = [u"Tecnicos"]
    model = Entrada
    template_name = 'supervision/entrada_list.html'

    def get_context_data(self, **kwargs):
        context = super(EntradaListView, self).get_context_data(**kwargs)
        context['detalleDepuracion'] = DetalleDepuracion.objects.all()
        return context

class EntradaCreateView(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    group_required = [u"admin", u"Supervisores",]
    model = Entrada
    form_class = EntradaForm
    template_name = 'supervision/entrada_add.html'

    def get_success_url(self):
        return reverse('entrada_detail', kwargs={'pk':self.object.id})

class EntradaUpdateView(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    group_required = [u"admin", u"Supervisores",]
    model = Entrada
    form_class = EntradaForm
    template_name = 'supervision/entrada_add.html'

    def get_success_url(self):
        return reverse('entrada_detail', kwargs={'pk':self.object.id})
    

class EntradaDetailView(GroupRequiredMixin, LoginRequiredMixin, DetailView):
    group_required = [u"admin", u"Supervisores"]
    model = Entrada
    template_name = 'supervision/entrada_detail.html'

    def get_context_data(self, **kwargs):
        context = super(EntradaDetailView, self).get_context_data(**kwargs)
        context['detalle_form'] = DetalleDepuracionForm(initial={'entrada': self.object})
        return context


""" Detalle de Entrada """
class DetalleDepuracionCreateView(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    group_required = [u"admin", u"Supervisores",]
    model = DetalleDepuracion
    form_class = DetalleDepuracionForm
    template_name = 'supervision/detalle_add.html'

    def get_success_url(self):
        return reverse('entrada_detail', kwargs={'pk':self.object.entrada.id})


class DetalleDepuracionUpdateView(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    group_required = [u"admin", u"Supervisores",]
    model = DetalleDepuracion
    form_class = DetalleDepuracionForm
    template_name = 'supervision/detalle_add.html'

    def get_success_url(self):
        return reverse('entrada_detail', kwargs={'pk':self.object.entrada.id})

# Quitar dipositivo del detalle
class DetalleDeleteView(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    group_required = [u"admin", u"Supervisores",]
    model = DetalleDepuracion
    template_name = 'supervision/detalle_delete.html'

    def get_success_url(self):
        return reverse('entrada_detail', kwargs={'pk':self.object.entrada.id})
	

templates/supervision/detalle_add.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} DETALLE {% endblock title %}

{% block stylesheets %}
{{ block.super }}

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <h1>Detalle</h1>
  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>... <small>Detalle</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          
          <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
          <div class="box-body  table-responsive">
            <form method="post" action="" class="form-horizontal form-label-left">
              <table class="table table-striped table-hover table-condensed">
                {% csrf_token %}
                {{form.as_table}}	
              </table>
              <button type="submit" class="btn btn-round btn-primary">Guardar</button>
            </form>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}

<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>

<!-- bootstrap-moment -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>

<!-- Mis Scripts -->
<script src="{% static 'build/mis_scripts.js' %}"></script>  

<!-- CSS -->
<style type="text/css">
  input:focus, textarea:focus, select:focus{
    /* background-color: rgb(0, 162, 255); */
    outline: 2px solid rgb(0, 174, 255);
  }
</style>

<script>
  $(document).ready(function() {
    
    init_select2();
    
  });
</script>


{% endblock javascripts %}

templates/supervision/detalle_delete.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} QUITAR DEL DETALLE {% endblock title %}

{% block stylesheets %}
{{ block.super }}

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <h1>Quitar dispositivo del detalle</h1>
  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-8 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2> <small>Datos</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          
          <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
          <div class="box-body">
            <form method="post" action="" class="form-horizontal form-label-left">
                <!-- <table class="table table-striped table-hover table-condensed"> -->
                    {% csrf_token %}
                    <strong class="count red">Desea quitar el dispositivo:</strong> {{ object.dispositivo }} <strong class="count red"> de la entrada #</strong> {{ object.entrada }}.
                    <br>
                    <br>
                    <strong class="count green">Con la cantidad: </strong>{{ object.cantidad }}.
                    <br>
                    <br>
                    <button type="submit" class="btn btn-xs btn-danger">Si, quitar</button>
                    <a class="btn btn-xs btn-success" href="{% url 'entrada_detail' object.entrada.id %}">Cancelar</a>
                <!-- </table> -->
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}


{% endblock javascripts %}

templates/supervision/entrada_add.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} NUEVA ENTRADA {% endblock title %}

{% block stylesheets %}
{{ block.super }}
<!-- alertas personalizadas -->
<link href="{% static 'vendors/alertas/css/alertify.css' %}" rel="stylesheet">
<link href="{% static 'vendors/alertas/css/themes/default.css' %}" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <h1>Entrada
      {% if object.id %}
         #{{ object.entrada }}
      {% endif %}
  </h1>
  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>... <small>datos de la entrada</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />

        {% if object.id %}
            {% if object.cerrar is False %}
          
                <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
                <div class="box-body  table-responsive">
                    <form method="post" action="" class="form-horizontal form-label-left" id="entrada-form" onSubmit="return validacion()">
                    <table class="table table-striped table-hover table-condensed">
                        {% csrf_token %}
                        {{form.as_table}}	
                    </table>
                    <button type="submit" class="btn btn-round btn-primary">Guardar</button>
                    </form>
                </div>
            {% else %}
                <h3>La entrada está cerrada</h3>
            {% endif %}
        {% else %}
            <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
            <div class="box-body  table-responsive">
                <form method="post" action="" class="form-horizontal form-label-left" id="entrada-form" onSubmit="return validacion()">
                <table class="table table-striped table-hover table-condensed">
                    {% csrf_token %}
                    {{form.as_table}}	
                </table>
                <button type="submit" class="btn btn-round btn-primary">Guardar</button>
                </form>
            </div>
        {% endif %}
          
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}

<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>

<!-- bootstrap-moment -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>

<!-- alertas personalizadas -->
<script src="{% static 'vendors/alertas/alertify.js' %}"></script>

<!-- Mis Scripts -->
<script src="{% static 'build/mis_scripts.js' %}"></script>  

<!-- CSS -->
<style type="text/css">
  input:focus, textarea:focus, select:focus{
    /* background-color: rgb(0, 162, 255); */
    outline: 2px solid rgb(0, 174, 255);
  }
</style>

<script>

    // VALIDACIÓN DEL FORMULARIO
    function validacion() {

      var Cerrar = $("#id_cerrar").is(":checked");
      var CreadoEnSuni = $("#id_creado_en_suni").is(":checked");
      var HojaImpresa = $("#id_hoja_impresa").is(":checked");
      var RegistroCorreo = $("#id_registro_en_correo").is(":checked");
      var NumeroKardex = document.getElementById("id_kardex").value;
      
      var estado = true;
      var pendientes ="";


    // Sí marca el check de Supervisión completada, se realizará una serie de validaciones.
    if(Cerrar){
      // Verifica que ya se haya creado en SUNI.
      if(!CreadoEnSuni){
        pendientes = pendientes + "<strong>SUNI: </strong> " + "Aún no está ingresado en SUNI... <br />";
        estado = false;
      }
      
      // Verifica que la hoja ya esté impresa.
      if(!HojaImpresa){
        pendientes = pendientes + "<strong>Hoja Impresa: </strong> " + "No hay hoja impresa!! <br />";
        estado = false;
      }


    // Verifica que existe un número ingresado en la casilla.
    if($.trim(NumeroKardex).length>0){
    }else{
      pendientes = pendientes + "<strong>Sin número: </strong> " + "Llene el campo de No. Kardex!! <br />";
        estado = false;
	}
      

      // Verifica que ya se haya registrado todo en correo electrónico.
      if(!RegistroCorreo){
        pendientes = pendientes + "<strong>Correo: </strong> " + "No hay registros en correo!! <br />";
        estado = false;
      }

    }

    if(estado){
    }else{
      alertify.alert("NO SE PUEDE CERRAR!", pendientes);
    }
    
    return estado;
};


</script>

<script>
  $(document).ready(function() {
    
    init_Switchery();
    init_select2();
    init_datapicker();

  });
    
</script>


{% endblock javascripts %}