apps/bodega/urls.py
from django.urls import path, include

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers

from .views import TarimaListView, TarimaUpdateView, TarimaDetailView, HistoricoInformeFormView, TarimaHistoricoRestList, \
    PasilloRestList, PasilloInformeFormView, TarimaRestList, ConsultaQrRest, \
    DespachoTriageListView, RegistrarTriageListView, ControlTriageDetailView, RegistrarTriageCreateView, DespachoTriageCreateView, \
    ConfirmarControlTriageUpdateView, ControlTriageCreateView, ControlTriageListView, ControlTriageCompletarUpdateView, \
    MaquinasListView, MaquinaHistoricoCreateView, MaquinaPerfilDetailView, MaquinaPerfilUpdateView, MaquinaHistoricoUpdateView
    
    
router = routers.SimpleRouter()
router.register(r'historico/tarimas', TarimaHistoricoRestList)
router.register(r'pasillo/tarimas', PasilloRestList)
router.register(r'tarimas/list', TarimaRestList)

urlpatterns = [
    
    # EQUIPAMIENTO
    path('tarima/list/', TarimaListView.as_view(), name='tarima_list'),
    #path('equipamiento/add/', EquipamientoCreateView.as_view(), name='equipamiento_add'),
    path('tarima/update/<int:pk>/', TarimaUpdateView.as_view(), name='tarima_update'),
    path('tarima/detail/<int:pk>/', TarimaDetailView.as_view(), name='tarima_detail'),
    path('tarima/informe/', HistoricoInformeFormView.as_view(), name='tarima_informe'),

    path('api/', include(router.urls)),

    # PASILLOS
    path('pasillo/informe/', PasilloInformeFormView.as_view(), name='pasillo_informe'),

    # DESDE SUNI
    path('tarima/qrs/', ConsultaQrRest.as_view(), name='tarima_qr_list'),

    
    # CONTROL DE TRIAGE
    path('entrega/triage/list/', DespachoTriageListView.as_view(), name='triage_entregados_list'),
    
    path('entrada/detail/<int:pk>/', ControlTriageDetailView.as_view(), name='entrada_triage_detail'),
    path('entrega/add/triage/', RegistrarTriageCreateView.as_view(), name='triage_add'),
    path('entrega/add/salida/triage/', DespachoTriageCreateView.as_view(), name='despachar_triage_add'),
    path('entrega/update/<int:pk>/', ConfirmarControlTriageUpdateView.as_view(), name='entrega_triage_update'),
    
    path('entrada/add/', ControlTriageCreateView.as_view(), name='entrada_triage_add'),
    path('entrada/update/<int:pk>/', ControlTriageCompletarUpdateView.as_view(), name='entrada_triage_update'),
    path('entrada/triage/list/', ControlTriageListView.as_view(), name='entrada_triage_list'),


    # CONTROL DE 
    path('control/maquinaria/list/', MaquinasListView.as_view(), name='maquinaria_list'),
    path('control/maquinaria/add/', MaquinaHistoricoCreateView.as_view(), name='maquinaria_historico_add'),
    path('control/maquinaria/detail/<int:pk>/', MaquinaPerfilDetailView.as_view(), name='maquinaria_detail'),
    path('control/maquinaria/update/<int:pk>/', MaquinaPerfilUpdateView.as_view(), name='reprogramar_servicio_update'),
    path('control/maquinaria/historico/update/<int:pk>/', MaquinaHistoricoUpdateView.as_view(), name='actualizar_info_servicio_update'),

    
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

#import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),

    #path('__debug__/', include(debug_toolbar.urls)),
    
    # Urls de las apps
    path('falta/', include('apps.faltas.urls')),
    path('', include('apps.evaluaciones.urls')),
    path('indicador/', include('apps.indicadores.urls')),
    path('perfil/', include('apps.registration.urls')),
    path('apuntes/', include('apps.apuntes.urls')),
    path('entregas/', include('apps.equipamientos.urls')),
    path('planificacion/', include('apps.tareas.urls')),
    path('supervision/', include('apps.supervision.urls')),
    path('bodega/', include('apps.bodega.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/bodega/models.py
from django.db import models
import datetime
from decimal import Decimal
from django.contrib.auth.models import User

from django.db.models import signals
from django.dispatch import receiver


# Modelo Abstracto para poder ser heredado
class ControlCreaciones(models.Model):
    creado = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    actualizado = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        abstract = True


class Pasillo(models.Model):
    pass

    def __str__(self):
        return str(self.id)

    def tarimas(self):
        return Tarima.objects.filter(sector__nivel__pasillo=self)


class Nivel(models.Model):
    nivel = models.CharField(max_length=1)
    pasillo = models.ForeignKey(Pasillo, on_delete=models.PROTECT, related_name='relNivelPasillo')

    def __str__(self):
        return '{}{}'.format(self.pasillo, self.nivel)

    def tarimas(self):
        return Tarima.objects.filter(sector__nivel=self)


class Sector(models.Model):
    sector = models.IntegerField(null=False)
    nivel = models.ForeignKey(Nivel, related_name='relSectorNivel', on_delete=models.CASCADE)

    def __str__(self):
        return '{nivel}-{sector}'.format(nivel=self.nivel, sector=self.sector)



""" 
Estado de la Tarima:
-En Uso
-Libre = Vacía
-Dañada
"""
class EstadoTarima(models.Model):
    estado = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.estado)


class Tarima(ControlCreaciones):
    sector = models.ForeignKey(Sector, on_delete=models.PROTECT, null=True, blank=True, related_name='relTarimaSector')
    contenido = models.TextField(null=True, blank=True)
    estado = models.ForeignKey(EstadoTarima, on_delete=models.PROTECT, null=True, blank=True, related_name='relTarimaEstado')
    editado_por = models.ForeignKey(User, related_name='relTarimaUsuario', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class HistoricoTarima(ControlCreaciones):
    tarima = models.ForeignKey(Tarima, on_delete=models.PROTECT, null=True, blank=True, related_name='relHistoricoTarimaTarima')
    fecha = models.DateField(default=datetime.datetime.now, null=True, blank=True)
    sector = models.ForeignKey(Sector, on_delete=models.PROTECT, null=True, blank=True, related_name='relHistoricoTarimaSector')
    contenido = models.TextField(null=True, blank=True)
    estado = models.ForeignKey(EstadoTarima, on_delete=models.PROTECT, null=True, blank=True, related_name='relHistoricoTarimaEstado')
    editado_por = models.ForeignKey(User, related_name='relHistoricoTarimaUsuario', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)



""" Agregar cambio al histórico.
*Colocando False se le indica que sólo sí no existe la -created- en el diccionario entre al if o True si ya existe.
"""
@receiver(signals.pre_save, sender=Tarima) 
def enviar_historico(sender, instance, **kwargs):
    
    #if kwargs.get('updated', True):
    if not instance._state.adding:
        print ("______________________________ ACTUALIZAR_____________________________")

        modificado = False

        # id de la tarima que tiene movimiento
        id_tarima = instance.id

        # Validar si no se seleccionó sector
        if (instance.sector):
            sector_tarima = Sector.objects.get(pk=instance.sector.id) # Si seleccionó obtener el valor
            
            if (Tarima.objects.get(pk=id_tarima).sector != None):
                antiguo_sector_tarima = Tarima.objects.get(pk=id_tarima).sector
            else:
                antiguo_sector_tarima = None

        else:
            sector_tarima = None # Sino selecciono marcar como None o nulo
            antiguo_sector_tarima = None
        
        # Validar si no se seleccionó estado
        if (instance.estado):
            estado_tarima = EstadoTarima.objects.get(pk=(instance.estado.id)) # Si seleccionó obtener el valor

            if(Tarima.objects.get(pk=id_tarima).estado != None):
                antiguo_estado_tarima = Tarima.objects.get(pk=id_tarima).estado
            else:
                antiguo_estado_tarima = None

        else:
            estado_tarima = None # Sino selecciono marcar como None o nulo
            antiguo_estado_tarima = None

        contenido_tarima = Tarima.objects.get(pk=id_tarima).contenido # Obtener el valor
        UsuarioTarima = User.objects.get(pk=Tarima.objects.get(pk=id_tarima).editado_por.id) # Obtener el valor

        # Valores antiguos print("\nid: " + str(id_tarima) + " -Sector: " + str(sector_tarima) + " -Contenido:" + str(contenido_tarima) + " -Estado: " + str(estado_tarima))
        # Valores nuevos print("\nid: " + str(instance.id) + " -Sector: " + str(instance.sector) + " -Contenido:" + str(instance.contenido) + " -Estado: " + str(instance.estado) + "\n\n")

        # print(str(antiguo_sector_tarima) + " --- " + str(instance.sector))
        # print(str(antiguo_estado_tarima) + " --- " + str(instance.estado))
        
        # Verificar si algún dato cambió
        if (antiguo_sector_tarima != instance.sector):
            modificado = True

        if (contenido_tarima != instance.contenido):
            modificado = True
        
        if (antiguo_estado_tarima != instance.estado):
            modificado = True
        
        
        # Si la variable es True es porque sí hubieron cambios y se creará el registro en el histórico.
        if (modificado):
            HistoricoTarima.objects.create(tarima=instance, sector=sector_tarima, contenido=instance.contenido, estado=estado_tarima, editado_por=UsuarioTarima)
        



# ******** CONTROL DE TRIAGE ********

""" Dispositivo
CPU, MONITOR, TECLADO, MOUSE, LAPTOP, TABLET, DISCO DURO
"""
class DispositivosTriage(models.Model):
    dispositivo = models.CharField(max_length=100, null=False, blank=False)
    identificador = models.CharField(max_length=15, null=True, blank=True)
    
    def __str__(self):
        return str(self.dispositivo)

""" Tipo de Entrada
Donación, Compra, Renovación, Reingreso, Etc.
"""
class TiposEntrada(models.Model):
    tipo = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return str(self.tipo)

""" Estado de la Entrada
Útil o Repuesto
"""
class InventarioEntrada(models.Model):
    tipo = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return str(self.tipo)

class ControlTriage(ControlCreaciones):
    no_entrada = models.PositiveSmallIntegerField(null=False, unique=True)
    fecha_entrada = models.DateField(default=datetime.datetime.now, null=True, blank=True)
    ingresa_como = models.ForeignKey(TiposEntrada, on_delete=models.PROTECT, null=True, blank=True, related_name='relControlTriageTiposEntrada')
    
    completado = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.no_entrada)
    
class RegistrarTriage(models.Model):
    no_entrada = models.ForeignKey(ControlTriage, on_delete=models.PROTECT, null=True, blank=True, related_name='relRegistrarTriageControlTriage')
    dispositivo = models.ForeignKey(DispositivosTriage, on_delete=models.PROTECT, null=True, blank=True, related_name='relRegistrarTriageDispositivosTriage')
    cantidad = models.PositiveSmallIntegerField(null=False)
    a_inventario_de = models.ForeignKey(InventarioEntrada, on_delete=models.PROTECT, null=True, blank=True, related_name='relRegistrarTriageInventarioEntrada')

    creado_por = models.ForeignKey(User, related_name='relRegistrarTriageCreadoPor', on_delete=models.CASCADE, null=True, blank=True)
    fecha_creacion = models.DateField(default=datetime.datetime.now, null=True, blank=True)

    rando_inicia = models.PositiveSmallIntegerField(null=False)
    rando_termina = models.PositiveSmallIntegerField(null=False)

    def __str__(self):
        return '{} - {}: {}'.format(self.no_entrada, self.dispositivo, self.cantidad)
    


class DespachoTriage(models.Model):
    no_entrada = models.ForeignKey(ControlTriage, on_delete=models.PROTECT, null=True, blank=True, related_name='relDespachoTriageControlTriage')
    dispositivo = models.ForeignKey(DispositivosTriage, on_delete=models.PROTECT, null=True, blank=True, related_name='relDespachoTriageDispositivosTriage')
    cantidad = models.PositiveSmallIntegerField(null=False)
    a_inventario_de = models.ForeignKey(InventarioEntrada, on_delete=models.PROTECT, null=True, blank=True, related_name='relDespachoTriageInventarioEntrada')

    rando_inicia = models.PositiveSmallIntegerField(null=False)
    rando_termina = models.PositiveSmallIntegerField(null=False)

    fecha_entrega = models.DateField(default=datetime.datetime.now, null=True, blank=True)
    entrega = models.ForeignKey(User, related_name='relDespachoTriageReimpresosEntrega', on_delete=models.CASCADE, null=True, blank=True)
    recibe = models.ForeignKey(User, related_name='relDespachoTriageReimpresosRecibe', on_delete=models.CASCADE)
    firma_digital = models.BooleanField(default=False, verbose_name='Confirmar de recibido')

    def __str__(self):
        return '{}'.format(self.no_entrada)



class ControlTriageReimpresos(ControlCreaciones):
    dispositivo = models.ForeignKey(DispositivosTriage, on_delete=models.PROTECT, null=True, blank=True, related_name='relControlTriageReimpresosDispositivosTriage')
    autorizado_por = models.ForeignKey(User, related_name='relControlTriageReimpresosAutorizadoPor', on_delete=models.CASCADE)
    motivo_reimpresion = models.TextField(verbose_name='Motivo de la Reimpresión', null=True, blank=True)
    
    fecha_reimpresion = models.DateField(default=datetime.datetime.now, null=True, blank=True)
    triage = models.PositiveSmallIntegerField(null=False)    
    
    fecha_entrega = models.DateField(default=datetime.datetime.now, null=True, blank=True)

templates/bodega/entrada_triage_add.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} NUEVA ENTRADA {% endblock title %}

{% block stylesheets %}
{{ block.super }}
  <!-- alertas personalizadas -->
  <link href="{% static 'vendors/alertas/css/alertify.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/alertas/css/themes/default.css' %}" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <h1>Entrada</h1>
  <a class="btn btn-round btn-warning" href="{% url 'entrada_triage_list' %}"><i class="fa fa-reply"></i> Listar entradas</a>

    <br>
    {% if object.id %}
        <a class="btn btn-round btn-success" href="{% url 'entrada_triage_detail' object.id %}"><i class="fa fa-reply"></i> Ir a Detalle de la Entrada</a>
        <br>
       <strong> Fecha:</strong> {{ object.fecha_entrada }}
       <br>
       <strong>Ingresado como:</strong> {{ object.ingresa_como }}
    {% endif %}


  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>... <small>datos de la entrada</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          
          <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
          <div class="box-body  table-responsive">
            <form method="post" action="" class="form-horizontal form-label-left" id="movimiento-form" onSubmit="return validacion()">
              <table class="table table-striped table-hover table-condensed">
                {% csrf_token %}
                {{form.as_table}}	
              </table>
              <button type="submit" class="btn btn-round btn-primary">Guardar</button>
            </form>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}

<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>

<!-- bootstrap-moment -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>

<!-- Mis Scripts -->
<script src="{% static 'build/mis_scripts.js' %}"></script>

<!-- alertas personalizadas -->
<script src="{% static 'vendors/alertas/alertify.js' %}"></script>

<!-- CSS -->
<style type="text/css">
  input:focus, textarea:focus, select:focus{
    /* background-color: rgb(0, 162, 255); */
    outline: 2px solid rgb(0, 174, 255);
  }
</style>



<script>
  $(document).ready(function() {
    
    init_Switchery();
    init_select2();
    init_datapicker();

  });
</script>


<script>
// VALIDACIÓN DEL FORMULARIO
  function validacion() {
    
      var completar = $("#id_completado").is(":checked");
      var estado = true;
      

      if(completar == true){

            "{% for pendiente in Existencia %}"
            "{{ pendiente.dispositivo__dispositivo }}"
                "{{ pendiente.total }}"
                
                var pendientes = parseInt("{{ pendiente.total }}", 10);
                    if(pendientes > 0){
                        alertify.success("Imposible completar, tiene " + pendientes + " triage de {{pendiente.dispositivo__dispositivo}} pendientes de entregar."); 
                        estado = false
                        return estado;
                    }
            "{% endfor %}"
      }
     
  return estado;

  };
</script>

{% endblock javascripts %}

templates/bodega/entrega_triage_add.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} NUEVA ENTREGA DE TRIAGE {% endblock title %}

{% block stylesheets %}
{{ block.super }}
  <!-- alertas personalizadas -->
  <link href="{% static 'vendors/alertas/css/alertify.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/alertas/css/themes/default.css' %}" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <h1>Entrega de Triage</h1>
  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>... <small>datos de la entrega</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          
          <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
          <div class="box-body  table-responsive">
            <form method="post" action="" class="form-horizontal form-label-left" id="movimiento-form" onSubmit="return validacion()">
              <table class="table table-striped table-hover table-condensed">
                {% csrf_token %}
                {{form.as_table}}	
              </table>
              <button type="submit" class="btn btn-round btn-primary">Guardar</button>
            </form>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}

<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>

<!-- bootstrap-moment -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>

<!-- Mis Scripts -->
<script src="{% static 'build/mis_scripts.js' %}"></script>

<!-- alertas personalizadas -->
<script src="{% static 'vendors/alertas/alertify.js' %}"></script>

<!-- CSS -->
<style type="text/css">
  input:focus, textarea:focus, select:focus{
    /* background-color: rgb(0, 162, 255); */
    outline: 2px solid rgb(0, 174, 255);
  }
</style>



<script>
  $(document).ready(function() {
    
    init_Switchery();
    init_select2();
    init_datapicker();

  });
</script>


<script>
// VALIDACIÓN DEL FORMULARIO
  function validacion() {
    
      var cantidad = parseInt($("#id_cantidad").val(), 10);
      var inicia = parseInt($("#id_rando_inicia").val(), 10);
      var termina = parseInt($("#id_rando_termina").val(), 10);

      var comparar = 0;
      var estado = false;    

      // Validar que las cajas de texto no se encuentre vacías
      if(inicia != "" && termina !=""){
        comparar = inicia + cantidad - 1;
        
        // Validar si el rando ingresado es correcto.
        if(termina == comparar){

          var cadena = "Se registra el rango de triage: " + inicia + " al " + termina;
          alertify.success(cadena); 
          estado = true;

        }else{
          estado = false;
          alertify.alert("El rando inicia en: " + inicia + " por lo que debe finalizar en: " + comparar);
          $('#id_rando_termina').val(comparar);
        }

      }else{
        estado = false;
        alertify.alert("Debe especificar el rango!");
      }
      
  
  return estado;

  };
</script>

{% endblock javascripts %}

templates/bodega/historico_servicio_update.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} ACTUALIZAR INFO DE SERVICIO {% endblock title %}

{% block stylesheets %}
{{ block.super }}
  <!-- alertas personalizadas -->
  <link href="{% static 'vendors/alertas/css/alertify.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/alertas/css/themes/default.css' %}" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <h1>Servicio</h1>
  <a class="btn btn-round btn-warning" href="{% url 'maquinaria_list' %}"><i class="fa fa-reply"></i> Máquinas </a>

    <br>
    {% if object.id %}
        <a class="btn btn-round btn-success" href="{% url 'maquinaria_detail' object.maquina.id %}"><i class="fa fa-reply"></i> Ver el detalle de la Máquina</a>
        <br>
    {% endif %}


  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>... <small>Actualizar Información del Servicio</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          
          <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
          <div class="box-body  table-responsive">
            <form method="post" action="" class="form-horizontal form-label-left" id="movimiento-form">
              <table class="table table-striped table-hover table-condensed">
                {% csrf_token %}
                {{form.as_table}}	
              </table>
              <button type="submit" class="btn btn-round btn-primary">Guardar</button>
            </form>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}

<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>

<!-- bootstrap-moment -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>

<!-- Mis Scripts -->
<script src="{% static 'build/mis_scripts.js' %}"></script>

<!-- alertas personalizadas -->
<script src="{% static 'vendors/alertas/alertify.js' %}"></script>

<!-- CSS -->
<style type="text/css">
  input:focus, textarea:focus, select:focus{
    /* background-color: rgb(0, 162, 255); */
    outline: 2px solid rgb(0, 174, 255);
  }
</style>



<script>
  $(document).ready(function() {
    
    init_Switchery();
    init_select2();
    init_datapicker();

  });
</script>


{% endblock javascripts %}

templates/bodega/reprogramar_servicio_update.html
{% extends "base/base_site.html" %}
{% load static  %}

{% block title %} REPROGRAMAR SERVICIO {% endblock title %}

{% block stylesheets %}
{{ block.super }}
  <!-- alertas personalizadas -->
  <link href="{% static 'vendors/alertas/css/alertify.css' %}" rel="stylesheet">
  <link href="{% static 'vendors/alertas/css/themes/default.css' %}" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

<div class="right_col" role="main">
  <!-- top tiles -->
  <a class="btn btn-round btn-warning" href="{% url 'maquinaria_list' %}"><i class="fa fa-reply"></i> Máquinas </a>

    <br>
    {% if object.id %}
        <a class="btn btn-round btn-success" href="{% url 'maquinaria_detail' object.id %}"><i class="fa fa-reply"></i> Ver el detalle de la Máquina</a>
        <br>
       <strong> Fecha Programada Actual:</strong> {{ object.servicio_programado }}
       <br>
       <strong>Maquinaria:</strong> {{ object.maquina }}
       <br>
       <strong>Encargado:</strong> {{ object.encargado }}
    {% endif %}


  <!-- /top tiles -->
  
  <br />
  
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>... <small>Reprogramar Servicio</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          
          <!-- Aquí se puede agregar contenido para que aparezca en la ventanita -->
          <div class="box-body  table-responsive">
            <form method="post" action="" class="form-horizontal form-label-left" id="movimiento-form">
              <table class="table table-striped table-hover table-condensed">
                {% csrf_token %}
                {{form.as_table}}	
              </table>
              <button type="submit" class="btn btn-round btn-primary">Guardar</button>
            </form>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  
</div>


{% endblock content %}

{% block javascripts %}
{{ block.super}}

<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>

<!-- bootstrap-moment -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>

<!-- Mis Scripts -->
<script src="{% static 'build/mis_scripts.js' %}"></script>

<!-- alertas personalizadas -->
<script src="{% static 'vendors/alertas/alertify.js' %}"></script>

<!-- CSS -->
<style type="text/css">
  input:focus, textarea:focus, select:focus{
    /* background-color: rgb(0, 162, 255); */
    outline: 2px solid rgb(0, 174, 255);
  }
</style>



<script>
  $(document).ready(function() {
    
    init_Switchery();
    init_select2();
    init_datapicker();

  });
</script>


{% endblock javascripts %}